#############################################################################
# NOTICE                                                                    #
#                                                                           #
# This software (or technical data) was produced for the U.S. Government    #
# under contract, and is subject to the Rights in Data-General Clause       #
# 52.227-14, Alt. IV (DEC 2007).                                            #
#                                                                           #
# Copyright 2022 The MITRE Corporation. All Rights Reserved.                #
#############################################################################

#############################################################################
# Copyright 2022 The MITRE Corporation                                      #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#    http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-manager
spec:
  template:
    spec:
      containers:
        - name: workflow-manager
          env:
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KEYSTORE_PASSWORD
                  name: wfm-https
                  optional: false
          volumeMounts:
            - name: https-cert
              mountPath: /run/secrets/https_keystore
              subPath: cert.p12
              readOnly: true
          ports:
            - containerPort: 8443
      volumes:
        - name: https-cert
          secret:
            secretName: wfm-https
            optional: false
